version: '3.8'
networks:
  mynet:
    driver: bridge
services:
  database-service:
    container_name: database-container
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    networks:
      - mynet
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  order-service:
    container_name: order-service-container
    depends_on:
      - rabbitmq3
      - database-service
    build: ./order-service
    volumes:
      - ./order-service:/order-service
      - ~/.m2:/root/.m2
    working_dir: /order-service
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - 8080:8080
    networks:
      - mynet
    command: mvn clean spring-boot:run
  payment-service:
    container_name: payment-service-container
    depends_on:
      - rabbitmq3
      - database-service
    build: ./payment-service
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    volumes:
      - ./payment-service:/payment-service
      - ~/.m2:/root/.m2
    working_dir: /payment-service
    ports:
      - 8081:8080
    networks:
      - mynet
    command: mvn clean spring-boot:run
  inventory-service:
    container_name: inventory-service-container
    depends_on:
      - rabbitmq3
      - database-service
    build: ./inventory-service
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    volumes:
      - ./inventory-service:/inventory-service
      - ~/.m2:/root/.m2
    working_dir: /inventory-service
    ports:
      - 8086:8080
    networks:
      - mynet
    command: mvn clean spring-boot:run
  authentication-service:
    container_name: authentication-service-container
    depends_on:
      - database-service
    build: ./authentication-service
    volumes:
      - ./authentication-service:/authentication-service
      - ~/.m2:/root/.m2
    working_dir: /authentication-service
    networks:
      - mynet
    ports:
      - 8090:8080
    command: mvn clean spring-boot:run
  keycloak:
    container_name: keycloak_container
    depends_on:
      - database-service
    image: jboss/keycloak:4.8.3.Final
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: database-service
      DB_DATABASE: accountsv_db
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      DB_PORT: 3306
      KEYCLOAK_PASSWORD: 123
    networks:
      - mynet
    ports:
      - 8889:8080
  rabbitmq3:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    networks:
      - mynet
