version: '3.8'
networks:
  mynet:
    driver: bridge
services:
  database-service:
    container_name: database-container
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    networks:
      - mynet
    volumes:
      - ./database:/docker-entrypoint-initdb.d
#  order-service:
#    depends_on:
#      - database-service
#    build: ./order-service
#    volumes:
#      - ./order-service:/order-service
#      - ~/.m2:/root/.m2
#    working_dir: /order-service
#    ports:
#      - 8080:8080
#    networks:
#      - mynet
#    command: mvn clean spring-boot:run
#  payment-service:
#    depends_on:
#      - database-service
#    build: ./payment-service
#    volumes:
#      - ./payment-service:/payment-service
#      - ~/.m2:/root/.m2
#    working_dir: /payment-service
#    ports:
#      - 8081:8080
#    networks:
#      - mynet
#    command: mvn clean spring-boot:run
  account-service:
    container_name: account-service-container
    depends_on:
      - database-service
    build:  ./account-service
    volumes:
      - ./account-service:/account-service
      - ~/.m2:/root/.m2
    working_dir: /account-service
    networks:
      - mynet
    ports:
      - 8000:8000
    command: mvn clean spring-boot:run
  keycloak:
    container_name: keycloak_container
    depends_on:
      - database-service
    image: jboss/keycloak:4.8.3.Final
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: database-service
      DB_DATABASE: accountsv_db
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      DB_PORT: 3306
      KEYCLOAK_PASSWORD: Pa55w0rd
    networks:
      - mynet
    ports:
      - 8888:8080

