version: '3.8'
networks:
  mynet:
    driver: bridge
services:
  database-service:
    container_name: database-container
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  order-service:
    depends_on:
      - database-service
    build: ./order-service
    volumes:
      - ./order-service:/order-service
      - ~/.m2:/root/.m2
    working_dir: /order-service
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
  payment-service:
    depends_on:
      - database-service
    build: ./payment-service
    volumes:
      - ./payment-service:/payment-service
      - ~/.m2:/root/.m2
    working_dir: /payment-service
    ports:
      - 8081:8080
    command: mvn clean spring-boot:run
  keycloak:
    depends_on:
      - database-service
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: database-service
      DB_DATABASE: accountsv_db
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8888:8080

